#!/usr/bin/env python3
"""
Imports the option-tile icons from the reference library into public/.

Source: Rings-Organised/_icons/, which ships one icon per selectable value,
named identically to the folder that holds that value's renders. That pairing
is the whole reason this is four lines of copying rather than a mapping table
— `_icons/head/classic-halo.png` goes with `.../classic-halo/`, and the id in
lib/ring/heads.ts is the same string again. Nothing to keep in step.

Band, head and shape arrive as PNG and are re-encoded to WebP at 200px; metal
is SVG and is copied through untouched, because a vector already scales.

The re-encode is not housekeeping. Forty-six icons load on the builder, and the
raster ones arrive at 417 KB — of which the ten shape icons alone are 171 KB,
because they ship at 1300x1024 to be drawn in an 86px tile. That is a hundred
and fifty times more pixels than the tile can show. At 200px WebP the whole set
lands around 40 KB, which is the difference between the option rails being a
rounding error on the page weight and being the largest thing on it.

200px rather than 172 (2x of 86) for a little headroom if the tiles ever grow.

Content-hashed filenames, for the same reason the ring artwork is — see the
long note in scripts/import-ring-images.py. next.config.ts holds images for a
year, so overwriting one in place would never reach anybody who had already
loaded it.

Run: python3 scripts/import-ring-icons.py
"""

import hashlib
import io
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required:  pip3 install Pillow")

# 2x the option tile's 86px, plus headroom.
EDGE = 200
QUALITY = 82

SRC = os.path.expanduser("~/Desktop/Rings-Organised/_icons")
OUT = "public/ring-builder/icons"
MANIFEST = "lib/ring/generated/icon-manifest.ts"
KINDS = ("band", "head", "shape", "metal")


def main():
    if not os.path.isdir(SRC):
        sys.exit(f"icon source not found: {SRC}")

    entries = []
    for kind in KINDS:
        src = os.path.join(SRC, kind)
        dst = os.path.join(OUT, kind)
        os.makedirs(dst, exist_ok=True)

        # Clear previous hashed builds so public/ does not accumulate every
        # version ever imported.
        for name in os.listdir(dst):
            os.remove(os.path.join(dst, name))

        for name in sorted(os.listdir(src)):
            if name.startswith("."):
                continue
            stem, ext = os.path.splitext(name)
            data = open(os.path.join(src, name), "rb").read()

            if ext.lower() != ".svg":
                # RGBA throughout: these are cut-outs, and flattening one onto
                # white would put a hard square behind it the moment a tile is
                # not white — which is exactly what the active state does.
                with Image.open(io.BytesIO(data)) as im:
                    im = im.convert("RGBA")
                    if max(im.size) > EDGE:
                        im.thumbnail((EDGE, EDGE), Image.LANCZOS)
                    buf = io.BytesIO()
                    im.save(buf, "WEBP", quality=QUALITY, method=6)
                    data = buf.getvalue()
                ext = ".webp"

            hashed = f"{stem}.{hashlib.sha1(data).hexdigest()[:8]}{ext}"
            with open(os.path.join(dst, hashed), "wb") as fh:
                fh.write(data)
            entries.append((f"{kind}/{stem}", hashed))

    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    lines = [
        "// Generated by scripts/import-ring-icons.py — do not edit by hand.",
        "//",
        "// The option-tile icons, one per selectable value, keyed exactly as the",
        "// option ids are. Content-hashed filenames because next.config.ts holds",
        "// images for a year — see the note in scripts/import-ring-images.py.",
        "",
        "export const ICON_FILES: Record<string, string> = {",
    ]
    for key, filename in entries:
        lines.append(f'  "{key}": "{filename}",')
    lines.append("};")
    with open(MANIFEST, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"{len(entries)} icons -> {OUT}")
    print(f"manifest written to {MANIFEST}")


if __name__ == "__main__":
    main()
