import type { SettingId } from "./config";
import type { ShapeId } from "./shapes";
import { PHOTO_FILES } from "./generated/photo-manifest";

/**
 * Real photography for the option tiles.
 *
 * The live 3D is very good at answering "what does MY combination look like,
 * turned in the light" — that is the thing no photograph can do, because no
 * photograph exists of your particular stone in your particular setting in your
 * particular metal. It is much less good at looking like a photograph, and it
 * never will be: a real-time procedural render on a phone GPU is not competing
 * with a lit product shot on equal terms.
 *
 * So the two do different jobs. Tiles are a shop window — they need to look
 * like the finished piece and make somebody want it. The viewer is a
 * configurator — it needs to be accurate and responsive. Worth noting that the
 * reference site everyone points at does exactly this: its option tiles are
 * static imagery and the WebGL view is opt-in behind a play control, not the
 * default.
 *
 * Anything missing here simply falls back to the live render, so the builder
 * works today and improves one photograph at a time. Nothing breaks while the
 * shot list is being worked through.
 *
 * ── Shooting notes ──
 *
 * File naming is strict, because these paths are resolved by id:
 *   settings:  /ring-builder/settings/{settingId}.jpg
 *   shapes:    /ring-builder/shapes/{shapeId}.jpg
 *
 * All lowercase, hyphens, no spaces. Square crop, 1200 × 1200, under 250 KB.
 * Shoot every setting in the SAME metal and the SAME centre stone size so the
 * grid reads as one family — the tile is there to show the setting, and a
 * change of metal between tiles reads as noise. Platinum with a 1.00ct round is
 * the sensible constant, since that is the default configuration.
 *
 * Three-quarter angle, slightly above, matching the viewer's default camera, so
 * clicking a tile is continuous rather than a jump cut. Plain light ground —
 * the tiles sit on white (see `surface.ts`), so a white sweep matches.
 */

/**
 * Artwork we have. Anything absent falls back to the live render.
 *
 * Generated by `scripts/import-ring-images.mjs` from the engraved ring set —
 * transparent cut-outs, so they drop onto the tile ground cleanly rather than
 * carrying a baked-in background that would have to be re-cut if the surface
 * colour ever changed.
 *
 * Provenance is recorded in the import script rather than here, because that is
 * where it would otherwise be lost. Replacing these with Alpoe's own product
 * photography needs nothing but new files at the same paths — see
 * `docs/ring-builder-photography.md` for the shot list.
 */
const SETTING_PHOTOS: Partial<Record<SettingId, true>> = {
  solitaire: true, rubover: true, halo: true, "grain-set": true,
  "hidden-halo": true, "double-halo": true, "knife-edge": true,
  trilogy: true, "side-stone": true, "channel-set": true,
  "split-shank": true, crossover: true, cluster: true, vintage: true,
  trellis: true, tension: true, "toi-et-moi": true,
};

/**
 * Loose stones for the centre-stone picker. A ring would be the wrong picture
 * here — the customer is choosing a cut, and seventeen near-identical rings
 * differing only in the stone's outline tells them far less than the stones
 * themselves do.
 */
const SHAPE_PHOTOS: Partial<Record<ShapeId, true>> = {
  round: true, oval: true, cushion: true, emerald: true,
  pear: true, radiant: true, marquise: true, asscher: true,
};

/**
 * Builds the URL with its content hash appended.
 *
 * The hash is what makes a re-export actually reach anybody. next.config.ts
 * sets a one-year `minimumCacheTTL`, so a browser that has fetched an image
 * once will not ask again — overwrite the file at the same path and every
 * returning visitor keeps the old one indefinitely.
 *
 * It lives in the filename rather than a `?v=` query string for two reasons:
 * Next rejects query strings on local images unless each is whitelisted in
 * `images.localPatterns`, which cannot work when the value changes with the
 * content; and some CDNs ignore query strings when caching, so `?v=` can fail
 * to bust anything. A different filename is unambiguous everywhere.
 */
function url(kind: "settings" | "shapes", id: string): string {
  const file = PHOTO_FILES[`${kind}/${id}`];
  return file ? `/ring-builder/${kind}/${file}` : `/ring-builder/${kind}/${id}.png`;
}

export function settingPhoto(id: SettingId): string | undefined {
  return SETTING_PHOTOS[id] ? url("settings", id) : undefined;
}

export function shapePhoto(id: ShapeId): string | undefined {
  return SHAPE_PHOTOS[id] ? url("shapes", id) : undefined;
}

/**
 * What still needs shooting. Surfaced in the builder's dev overlay rather than
 * buried in a document, so the gap stays visible while it is being closed.
 */
export function missingPhotos(settings: SettingId[], shapes: ShapeId[]) {
  return {
    settings: settings.filter((s) => !SETTING_PHOTOS[s]),
    shapes: shapes.filter((s) => !SHAPE_PHOTOS[s]),
  };
}
